---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  type: NodePort
  selector:
    app: sonar
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: sonar
          image: sonarqube:lts-community
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-data
              mountPath: /opt/sonarqube/data
            - name: sonar-logs
              mountPath: /opt/sonarqube/logs
            - name: sonar-extensions
              mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-pvc
        - name: sonar-logs
          emptyDir: {}
        - name: sonar-extensions
          emptyDir: {}
